//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goFriend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("goFriend.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appove/Reject group member.
        /// </summary>
        public static string AdminDesc {
            get {
                return ResourceManager.GetString("AdminDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AppearOnline {
            get {
                return ResourceManager.GetString("AppearOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asked to join the group.
        /// </summary>
        public static string AskedToJoinGroup {
            get {
                return ResourceManager.GetString("AskedToJoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string BasicInfos {
            get {
                return ResourceManager.GetString("BasicInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, date of birth, gender, email address, location.
        /// </summary>
        public static string BasicInfosDesc {
            get {
                return ResourceManager.GetString("BasicInfosDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChatEdit {
            get {
                return ResourceManager.GetString("ChatEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created the group at {1:H:mm}.
        /// </summary>
        public static string ChatMessageCreateChat {
            get {
                return ResourceManager.GetString("ChatMessageCreateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChatMessageIsDeleted {
            get {
                return ResourceManager.GetString("ChatMessageIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChatMessageIsImage {
            get {
                return ResourceManager.GetString("ChatMessageIsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChatNew {
            get {
                return ResourceManager.GetString("ChatNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Clear selection].
        /// </summary>
        public static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string CmdReset {
            get {
                return ResourceManager.GetString("CmdReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CmdSave {
            get {
                return ResourceManager.GetString("CmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set GPS position.
        /// </summary>
        public static string CmdSetGPSPos {
            get {
                return ResourceManager.GetString("CmdSetGPSPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common connection information.
        /// </summary>
        public static string CommonConnectionInfo {
            get {
                return ResourceManager.GetString("CommonConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password?.
        /// </summary>
        public static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups &amp; connection infos.
        /// </summary>
        public static string GroupConnectionsInfos {
            get {
                return ResourceManager.GetString("GroupConnectionsInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LatestVersionInfo {
            get {
                return ResourceManager.GetString("LatestVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LatestVersionWarn {
            get {
                return ResourceManager.GetString("LatestVersionWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to sign in or create an account to continue.
        /// </summary>
        public static string LoginRequiredMsg {
            get {
                return ResourceManager.GetString("LoginRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map offline.
        /// </summary>
        public static string MapOffline {
            get {
                return ResourceManager.GetString("MapOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MapOfflineDesc {
            get {
                return ResourceManager.GetString("MapOfflineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since {0}.
        /// </summary>
        public static string MemberSince {
            get {
                return ResourceManager.GetString("MemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more messages.
        /// </summary>
        public static string MoreMessages {
            get {
                return ResourceManager.GetString("MoreMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not retrieve Name when sign in with Apple..
        /// </summary>
        public static string MsgAppleSignInNoName {
            get {
                return ResourceManager.GetString("MsgAppleSignInNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong in server side when registering user with Apple Sign In..
        /// </summary>
        public static string MsgAppleSignInServer {
            get {
                return ResourceManager.GetString("MsgAppleSignInServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the current changes and return to the initial state?.
        /// </summary>
        public static string MsgCancelConfirmation {
            get {
                return ResourceManager.GetString("MsgCancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgDataRequired {
            get {
                return ResourceManager.GetString("MsgDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string MsgErrConnection {
            get {
                return ResourceManager.GetString("MsgErrConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgErrUnableToTrack {
            get {
                return ResourceManager.GetString("MsgErrUnableToTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api connection error. Please relogin and try again!.
        /// </summary>
        public static string MsgErrWrongToken {
            get {
                return ResourceManager.GetString("MsgErrWrongToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to activate the Gps first..
        /// </summary>
        public static string MsgGpsDisabledWarning {
            get {
                return ResourceManager.GetString("MsgGpsDisabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Admin of the group..
        /// </summary>
        public static string MsgGroupSubscriptionAdmin {
            get {
                return ResourceManager.GetString("MsgGroupSubscriptionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an active user of the group..
        /// </summary>
        public static string MsgGroupSubscriptionNormal {
            get {
                return ResourceManager.GetString("MsgGroupSubscriptionNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not a member of the group. You can send the request to join the group if you have all necessary conditions..
        /// </summary>
        public static string MsgGroupSubscriptionNotMember {
            get {
                return ResourceManager.GetString("MsgGroupSubscriptionNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subsciption to this group is now in pending. You can check again later..
        /// </summary>
        public static string MsgGroupSubscriptionPending {
            get {
                return ResourceManager.GetString("MsgGroupSubscriptionPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscribtion is now inactive. Please check again later !.
        /// </summary>
        public static string MsgInactiveUserWarning {
            get {
                return ResourceManager.GetString("MsgInactiveUserWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to logout ?.
        /// </summary>
        public static string MsgLogoutConfirm {
            get {
                return ResourceManager.GetString("MsgLogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is mandatory.
        /// </summary>
        public static string MsgMandatoryField {
            get {
                return ResourceManager.GetString("MsgMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want really to modify your current subscription?.
        /// </summary>
        public static string MsgModifyConfirmation {
            get {
                return ResourceManager.GetString("MsgModifyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgMuteTitle {
            get {
                return ResourceManager.GetString("MsgMuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNewVersionAvailable {
            get {
                return ResourceManager.GetString("MsgNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoCamera {
            get {
                return ResourceManager.GetString("MsgNoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoGooglePlayServiceWarning {
            get {
                return ResourceManager.GetString("MsgNoGooglePlayServiceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoGpsWarning {
            get {
                return ResourceManager.GetString("MsgNoGpsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoGroupWarning {
            get {
                return ResourceManager.GetString("MsgNoGroupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoLocationServiceWarning {
            get {
                return ResourceManager.GetString("MsgNoLocationServiceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoLocationSuggestion {
            get {
                return ResourceManager.GetString("MsgNoLocationSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoLocationWarning {
            get {
                return ResourceManager.GetString("MsgNoLocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoPermissionChatEdit {
            get {
                return ResourceManager.GetString("MsgNoPermissionChatEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgNoPhotosPermission {
            get {
                return ResourceManager.GetString("MsgNoPhotosPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to save?.
        /// </summary>
        public static string MsgSaveConfirm {
            get {
                return ResourceManager.GetString("MsgSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MsgSavePosConfirm {
            get {
                return ResourceManager.GetString("MsgSavePosConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to approve the subscription?.
        /// </summary>
        public static string MsgSubscriptionApproveConfirm {
            get {
                return ResourceManager.GetString("MsgSubscriptionApproveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to reject the subscription?.
        /// </summary>
        public static string MsgSubscriptionRejectConfirm {
            get {
                return ResourceManager.GetString("MsgSubscriptionRejectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription successful.
        /// </summary>
        public static string MsgSubscriptionSuccessful {
            get {
                return ResourceManager.GetString("MsgSubscriptionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgTitleError {
            get {
                return ResourceManager.GetString("MsgTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MsgTitleInfo {
            get {
                return ResourceManager.GetString("MsgTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MuteFor15Mins {
            get {
                return ResourceManager.GetString("MuteFor15Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MuteFor1Hour {
            get {
                return ResourceManager.GetString("MuteFor1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MuteFor24Hours {
            get {
                return ResourceManager.GetString("MuteFor24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MuteFor8Hours {
            get {
                return ResourceManager.GetString("MuteFor8Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MuteUntilTurnOn {
            get {
                return ResourceManager.GetString("MuteUntilTurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to.
        /// </summary>
        public static string NavigateTo {
            get {
                return ResourceManager.GetString("NavigateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifiation.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to become a member of the group.
        /// </summary>
        public static string NotifSubscriptionApproved {
            get {
                return ResourceManager.GetString("NotifSubscriptionApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been refused joining the group.
        /// </summary>
        public static string NotifSubscriptionRejected {
            get {
                return ResourceManager.GetString("NotifSubscriptionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has modified the connection information while subscribing to the group.
        /// </summary>
        public static string NotifUpdateSubscriptionRequest {
            get {
                return ResourceManager.GetString("NotifUpdateSubscriptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OnlineEarlier {
            get {
                return ResourceManager.GetString("OnlineEarlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RadiusKM {
            get {
                return ResourceManager.GetString("RadiusKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RadiusM {
            get {
                return ResourceManager.GetString("RadiusM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RadiusNoLimit {
            get {
                return ResourceManager.GetString("RadiusNoLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelationshipComplicated {
            get {
                return ResourceManager.GetString("RelationshipComplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelationshipDivorced {
            get {
                return ResourceManager.GetString("RelationshipDivorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelationshipEngaged {
            get {
                return ResourceManager.GetString("RelationshipEngaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelationshipMarried {
            get {
                return ResourceManager.GetString("RelationshipMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelationshipSeparated {
            get {
                return ResourceManager.GetString("RelationshipSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelationshipSingle {
            get {
                return ResourceManager.GetString("RelationshipSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved with success.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type here to search.
        /// </summary>
        public static string SearchBarPlaceHolder {
            get {
                return ResourceManager.GetString("SearchBarPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show your location:.
        /// </summary>
        public static string ShowYourLocation {
            get {
                return ResourceManager.GetString("ShowYourLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting Love.
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s) ago..
        /// </summary>
        public static string SpentTimeInDays {
            get {
                return ResourceManager.GetString("SpentTimeInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h ago..
        /// </summary>
        public static string SpentTimeInHours {
            get {
                return ResourceManager.GetString("SpentTimeInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s) ago..
        /// </summary>
        public static string SpentTimeInMinutes {
            get {
                return ResourceManager.GetString("SpentTimeInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to group.
        /// </summary>
        public static string SubscribeGroup {
            get {
                return ResourceManager.GetString("SubscribeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SvcBackground {
            get {
                return ResourceManager.GetString("SvcBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SvcBackgroundContentText {
            get {
                return ResourceManager.GetString("SvcBackgroundContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone:.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Condtitions.
        /// </summary>
        public static string TermCondition {
            get {
                return ResourceManager.GetString("TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By proceeding with creating an account you agree to the GoFriend.
        /// </summary>
        public static string TermConditionMsg1 {
            get {
                return ResourceManager.GetString("TermConditionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string TermConditionMsg2 {
            get {
                return ResourceManager.GetString("TermConditionMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type message here....
        /// </summary>
        public static string TypeMsgHere {
            get {
                return ResourceManager.GetString("TypeMsgHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        public static string Unmute {
            get {
                return ResourceManager.GetString("Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
